[package]
name = "alor-gateway"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = { workspace = true }
anyhow = "1.0"
barter-data = { workspace = true }
chrono = { workspace = true }
futures = { workspace = true }
futures-util = { workspace = true }
parking_lot = { workspace = true }
rand = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
toml = "0.8"
axum = "0.7"
thiserror = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "signal", "time"] }
tokio-stream = { workspace = true }
tokio-tungstenite = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
uuid = { version = "1", features = ["v4", "fast-rng"] }

alor-scalping = { path = "../alor-scalping" }
alor-protocol = { path = "../alor-protocol" }

[dev-dependencies]
tempfile = "3"
